
name: CI Tests

on:
    push:
    pull_request:

jobs:
    ci_tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        env:
          CI_TESTING: "true"
          TNS_API_KEY: ${{ secrets.TNS_API_KEY }}
          TNS_ID: ${{ secrets.TNS_ID }}
          TNS_USERNAME: ${{ secrets.TNS_USERNAME }}
    
        strategy:
          matrix:
            include:
    
              - name: Python 3.10
                os: ubuntu-latest
                python: "3.10"
    
              - name: Python 3.11
                os: ubuntu-latest
                python: "3.11"
    
              - name: Python 3.11 Mac
                os: macos-latest
                python: "3.11"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install flake8 pytest tox
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
            - name: Run tests with tox
              run: tox -e test -- -v -s --capture=no

